@startuml
title Authorization of the client by the Client Credentials flow

participant "Welldata BE" as welldataBE
participant "We Are IDP" as weareidp

group We Are Client Credentials flow
 welldataBE->weareidp: https://openid.we-are-acc.vito.be/token body=grant_type=client_credentials&client_id=<>&client_secret=<>
 weareidp->welldataBE: access token and id token
end

@enduml
  