@startuml
title Creating a resource in the pod
actor "User" as user
participant "Welldata FE" as welldataFE
participant "Welldata BE" as welldataBE
participant "User Pod" as pod
participant "UMA Service" as umaservice

group Write to pod
 welldataBE->pod: GET https://<pod>/welldata/<resource>
 pod-->welldataBE: UMA_as_uri=<>, ticket=<>
 welldataBE->umaservice: POST https://uma.pod.datanutsbedrijf.be/token
 umaservice-->welldataBE: access token
 welldataBE->pod: POST https://<pod>/welldata/<resource>
end

@enduml
