# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.gidsopenstandaarden.welldata
canonical: https://gidsopenstandaarden.github.io/welldata-implementation-guide
url: https://gidsopenstandaarden.github.io/welldata-implementation-guide
name: welldata-implementation-guide
title: WellData Implementation Guide
# description: Example Implementation Guide for getting started with SUSHI
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: GPL-3.0-or-later # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gidsopenstandaarden
  url: https://www.gidsopenstandaarden.org
  # email: test@example.org

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
# dependencies:
#   nictiz.fhir.nl.r4.nl-core:
#     id: nlcore
#     uri: https://simplifier.net/packages/nictiz.fhir.nl.r4.nl-core
#     version: 0.10.0-beta.1
#
# dependencies:
#   hl7.fhir.us.core: 3.1.0
#   hl7.fhir.us.mcode:
#     id: mcode
#     uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
#     version: 1.0.0
#
#
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#
# pages:
#   index.md:
#     title: Example Home
#   implementation.xml:
#   examples.xml:
#     title: Examples Overview
#     simpleExamples.xml:
#     complexExamples.xml:

pages:
  index.md:
    title: Home
  overview.md:
    title: Overview
  primary-use-case.md:
    title: Primary Use Case
  identity.md:
    title: Identity and Idp
  identity-anonymous-login.md:
    title: Anonymous Login
  pod-access.md:
    title: Pod Access
  logging.md:
    title: Audit Logging
  research-data-overview.md:
    title: Research Data Overview
  launch.md:
    title: Launch & SSO
  static-data.md:
    title: Static Data (questionnaires)
  dynamic-data.md:
    title: Shared Dynamic Data
  technical-pod-access.md:
    title: Accessing the Pod
  technical-anonymous-login.md:
    title: Anonymous Login
  technical-anonymous-login-web-id.md:
    title: Anonymous Login with WEB-ID
  technical-hti-launch-compose.md:
    title: HTI - Composing a launch
  technical-hti-launch-receive.md:
    title: HTI - Receiving a launch
  technical-user-authentication.md:
    title: User Authentication
  technical-client-authentication.md:
    title: Client Authentication
  technical-research-data.md:
    title: Research Data Access
  hackathon-hti-launch.md:
    title: HTI Launch

#
#
# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array.
# For parameters defined by core FHIR see:
# http://build.fhir.org/codesystem-guide-parameter-code.html
# For parameters defined by the FHIR Tools IG see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
#
# parameters:
#   excludettl: true
#   validation: [allow-any-extensions, no-broken-links]
#
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Overview:
    Overview: overview.html
    Primary Use Case: primary-use-case.html
  Standards and Specification:
    Identity and IdP: identity.html
    Anonymous Login: identity-anonymous-login.html
    Pod Access: pod-access.html
    Launch: launch.html
    Audit logging: logging.html
  Research Data:
    Research Data Overview: research-data-overview.html
  Data models:
    Static Data: static-data.html
    Dynamic Data: dynamic-data.html
  FHIR Artifacts:
    Profiles: artifacts.html#2
    Extensions: artifacts.html#3
    Value Sets: artifacts.html#4
    Code Systems: artifacts.html#5
    Examples: artifacts.html#6
  Technical Walkthrough:
    Authenticating the user: technical-user-authentication.html
    Authenticating the application: technical-client-authentication.html
    Accessing the Pod: technical-pod-access.html
    Anonymous Login: technical-anonymous-login.html
    Anonymous Login with WEB-ID: technical-anonymous-login-web-id.html
    HTI, composing a launch: technical-hti-launch-compose.html
    HTI, receiving a launch: technical-hti-launch-receive.html
    Research Data Access: technical-research-data.html
  Hackathon:
    HTI Launch: hackathon-hti-launch.html
